### ISSUE TITLE
GAE for directed graphs + finding common patterns within a set of graphs

### ISSUE THREAD

**Issue by MTDzi** [tkipf/gae#10]
Hi Thomas,

First off: great work :)

Second: I would like to apply your GAE but for weighted directed graphs, without features.
I have a set of such graphs which (I hypothesize) contain similar sub-graphs and connection patterns between the nodes.
I would like to seek out those patterns, to then verify if they are indeed present (regardless of how I would do that).

My questions are:
1. I *think* I can adapt your approach by using a directed graph Laplacian:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csgraph.laplacian.html
I would use a sigmoid activation function, and minimize a logloss (although it won't really have anything to do with likelihood).
But am I missing something? Do you see a glaring hole in this kind of approach?

2. I wanted to look for the common patterns in my graphs -- let's call them {G_1, G_2, G_3, ...} -- by embedding the nodes into a common space, in which (I hope) the patterns would be easier to find. In your other repo (https://github.com/tkipf/gcn) you're suggesting that when dealing with multiple graphs, one might create a big adjacency matrix by concatenating the adjacency matrices of these graphs {G_1, G_2, G_3, ...}. How large can this concatenated adjacency matrix be? Have you reached a limit? And if so, what was it?

3. I was also wondering if you think it would be possible to look for patterns in the matrices W (self.vars['weights']) in the GraphConvolutionSparse layer (as an analogy to what you might do with filters in "classical" convolutional neural networks). Now that I think about it, it seems unlikely because the ordering of the rows/columns in the adjacency matrix is pretty much random. But maybe you've given this idea some thought and you'd be willing to point me to an answer: "yes, it can be done" or: "no, no way".

Please, let me know what you think, I would really appreciate it!

**Comment by MTDzi** [comment]
Thanks for your reply.

**Comment by tkipf** [comment]
> My understanding is that you input an adjacency matrix that looks like this, i.e. it's a "diagonal concatenation" of the adjacency matrices of graphs Q, V, and W.
> 
> @tkipf is that correct?

Yes :-)
