### ISSUE TITLE
Assertion error ismember

### ISSUE THREAD

**Issue by ana-kuznetsova** [tkipf/gae#19]
When I train gae with my own adjacency matrix, I receive assertion error in `ismember` function.

`Traceback (most recent call last):
  File "train.py", line 49, in <module>
    adj_train, train_edges, val_edges, val_edges_false, test_edges, test_edges_false = mask_test_edges(adj)
  File "build/bdist.linux-x86_64/egg/gae/preprocessing.py", line 99, in mask_test_edges
    assert ~ismember(val_edges_false, edges_all)
AssertionError
`

I load my matrix as 
`adj = sp.load_npz('adj.npz')`
by modifying `train.py`

And run gae as ` python2 train.py --features=0 `

What could be the reason and how to solve this?

**Comment by yjyGo** [comment]
I met the same problem:~ismember(val_edges_false, edges_all) AssertionError, do you resolve this?

**Comment by MinhAnhL** [comment]
I have the same problem when running it on the Cora example. 
Did you find a solution for that?

**Comment by codenameAggie** [comment]
I have the same issue

**Comment by kinkunchan** [comment]
I met the same problem:~ismember(val_edges_false, edges_all) AssertionError.

**Comment by meredith92** [comment]
same problem! any resolution?
