### ISSUE TITLE
No such file or directory: 'data/planetoid/ind.cora.x'

### ISSUE THREAD

**Issue by Shuolongbj** [tkipf/gae#2]
@tkipf thanks

python train.py
Traceback (most recent call last):
  File "train.py", line 40, in <module>
    adj, features = load_data(dataset_str)
  File "build/bdist.macosx-10.7-x86_64/egg/gae/input_data.py", line 19, in load_data
    objects.append(pkl.load(open("data/planetoid/ind.{}.{}".format(dataset, names[i]))))
IOError: [Errno 2] No such file or directory: 'data/planetoid/ind.cora.x'

**Comment by tkipf** [comment]
Thanks for catching this! Made some last-minute changes to the code yesterday and forgot to update the dataset path. This is now fixed with https://github.com/tkipf/gae/commit/229c1e9b04ef82056508eec8955552d5f333682f
