### ISSUE TITLE
what is the scipy version used for creating the input data

### ISSUE THREAD

**Issue by XuanHeIIIS** [tkipf/gae#23]
Hi tkipf,
I am trying to run your codes, but there are something wrong about the loaded data and this may caused by the discordance of the scipy version used for creating and loading data, so would you please show the scipy version you used or the codes you used to generate the data? Thanks~

![image](https://user-images.githubusercontent.com/11870070/50691273-2df3ac80-106b-11e9-9bf1-8583234132d5.png)

**Comment by tkipf** [comment]
Can you try scipy v.1.1.0? Or have you tried any other versions? Which version of scipy are you using?

**Comment by XuanHeIIIS** [comment]
@tkipf, I used scipy v.1.2.0 and i also tried v.1.1.0 and v.1.0.0, but this problem still exist...

**Comment by tkipf** [comment]
Interesting. Did you make any changes to the code? Try cloning the repository from scratch and see if the issue is still there.

**Comment by XuanHeIIIS** [comment]
@tkipf, Yes, I changed the data loader (input_data.py) from "pkl.load(open("data/ind.{}.{}".format(dataset, names[i])))" to "pkl.load(open("data/ind.{}.{}".format(dataset, names[i]), "rb"), encoding="bytes")" because of the UnicodeDecodeError. Do you think this will lead to the Error above ?

**Comment by tkipf** [comment]
Yes, this seems likely to be the cause. Please try python 2.7 and see if
the issue persists.

**Comment by XuanHeIIIS** [comment]
Hey tkipf,
Oh, yes, it works! Thank you very much!! :)
