### ISSUE TITLE
Can I get the same feature in this case?

### ISSUE THREAD

**Issue by JonasWangCN** [tkipf/gae#30]
Hi,
I got the features of the whole graph by extracting the features of each node and adding them together with `gae`, but now I have a question, I hope to get your help.
Now I have two graphs, and 60% of them have the same nodes (the same presentation features, the same adjacency relationship). But GCN processes one graph at a time, so I can only input two graphs into the network individually. If so, are 60% of the node feature of the two graphs the same? What can I do to ensure that 60% of the nodes have the same feature?

**Comment by tkipf** [comment]
You can feed both graphs jointly in a single batch like this:
https://github.com/tkipf/gcn/issues/4

**Comment by JonasWangCN** [comment]
Thank you for your reply.  Thank you very very much!!!!  I'll try it.

**Comment by JonasWangCN** [comment]
Thank you for your reply. Thank you very very much!!!! I'll try it.
And I wonder if there is no model that can save parameters and process new input Graphs yet?  Like `Cnn`
