### ISSUE TITLE
bach training

### ISSUE THREAD

**Issue by JonasWangCN** [tkipf/gae#34]
Sorry to keep asking the question! But now I have two questions to confirm.

1. I read your code carefully, and found that model training was just to find better weight parameter `self.vars['weights']`? (that is, only `self.vars['weights']`  is updated during the training process?)

2. I found that `feed_dict ` is unchanged in the training process. Now I have 1000 graphs(different adjacency matrix and variable number of nodes, but the same node's feature). So can I input data of different graphs in each epoch? If this is not possible, what is the reason?

Thanks for your patient answers!!!

**Comment by tkipf** [comment]
Yes and yes! You can certainly feed different graphs during training.

**Comment by JonasWangCN** [comment]
@tkipf Thanks for your reply. But I still have one problem. For graphs with different number of nodes, I fill in 0 vectors to ensure that the shape of the feature matrix is the same. So I can get the same `num_features` and `features_nonzero` and initialize the model(`GCNModelAE(placeholders, num_features, features_nonzero)`) with them?
       what's more, for different graphs, pos_weight and norm are different. But they are the initial parameters of the optimizer.
```
opt = OptimizerAE(preds=model.reconstructions,
                          labels=tf.reshape(tf.sparse_tensor_to_dense(placeholders['adj_orig'],
                                                                      validate_indices=False), [-1]),
                          pos_weight=pos_weight,
                          norm=norm)
```
      So how do I deal with the optimizer? I don't quite understand this question.

**Comment by tkipf** [comment]
In terms of features: training on different graphs only works if you have
meaningful node features (not just one-hot vectors corresponding to the
index of the node). How to get `pos_weight` in this case is a separate
issue. I recommend re-calculating this for every graph instance you feed
into the model (only feed one at a time for simplicity). We are also about
to release a new library for GAEs that use efficient negative sampling,
which avoids having to provide a weighted loss. This will be announced on
twitter (https://twitter.com/thomaskipf) once its ready.

**Comment by JonasWangCN** [comment]
@tkipf Yes,  the features of all nodes are meaningful. And according to your suggestion, should I reinitialize a new optimizer with `pos_weight ` of different graphs in every epoch?
In addition, I will keep an eye on your Twitter!

**Comment by tkipf** [comment]
No, but you could for example make `pos_weight` a placeholder and feed its
value together with every graph sample.

**Comment by JonasWangCN** [comment]
Thank you very much. I've already done that. I wish you every success in your work.

**Comment by wolfiex** [comment]
Regarding placeholders, may I ask what you changed?
I seem to keep getting `ValueError: setting an array element with a sequence.
`every time I try to do the same.
