### ISSUE TITLE
can't reproduce the results in the paper

### ISSUE THREAD

**Issue by haorannlp** [tkipf/gae#54]
The reported results on Citeseer with VGAE is 
AUC: 90.8(0.01), AP: 92.0(0.02). 
But I can only get AUC:86.6, AP: 88.7. 
on cora: 
reported: 91.4 92.6
my results: 84.8, 87.8
Is this difference caused by the specific datasplits? Or other settings?

**Comment by stefanosantaris** [comment]
Me neither. I am using exactly the same tensorflow implementation referred to the readme and same parameters mentioned on the paper but I have no luck. I see similar results with you @haorannlp.


@tkipf should we modify something in the code in order to reproduce the results?

**Comment by tkipf** [comment]
Thanks for bringing this up. This is potentially related to this pull request: https://github.com/tkipf/gae/pull/25 — I currently don’t have capacity to test this myself but you could try rolling back this change and see if it affects results on Citeseer.

**Comment by stefanosantaris** [comment]
I reverted the code and now I can efficiently reproduce the results of the paper. Thanks @tkipf. I will try to fix this and create a PR so that it is available on master.

**Comment by stefanosantaris** [comment]
Problem solved and a fix can be found here https://github.com/tkipf/gae/pull/55

**Comment by haorannlp** [comment]
Thank you guys!
