### ISSUE TITLE
a bug in ismember function?

### ISSUE THREAD

**Issue by certaincen** [tkipf/gae#9]
what does the function ismember in preprocessing.py used for?
to check whether an edge in an edge list?
For example:
a = [1, 2]
b = [[1,2], [2,3]]
 ismember(a, b) will return False, but edge [1,2] in already in  [[1,2], [2,3]].

**Comment by tkipf** [comment]
Thanks for catching this! This is indeed a bug and I have no idea what happened here (obviously a bug like this shouldn't happen with proper coding / unit testing practices).

The function should look like this instead:

```
    def ismember(a, b, tol=5):
        rows_close = np.all(np.round(a - b[:, None], tol) == 0, axis=-1)
        return np.any(rows_close)
```

I re-ran the Cora link prediction experiments with it and it looks like results are quite similar (I got slightly better results now than reported in the paper, but this could just be an outlier). I'll investigate this further. I'll push the changes in a sec (or feel free to make a pull request if you'd like to be listed as a contributor).

**Comment by tkipf** [comment]
Fixed with https://github.com/tkipf/gae/commit/cc5aa6c1194557a0a5c239ddab7a2a255af0f636
